/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.yale.comphealth.electron.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ObrAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ObrAvroModel\",\"namespace\":\"org.yale.comphealth.electron.models\",\"fields\":[{\"name\":\"msh_ts\",\"type\":\"long\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"msg_id\",\"type\":\"string\"},{\"name\":\"hl7\",\"type\":\"string\"},{\"name\":\"helix_rcv_ts\",\"type\":\"long\"},{\"name\":\"tz_offset\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long msh_ts;
  @Deprecated public java.lang.CharSequence source;
  @Deprecated public java.lang.CharSequence msg_id;
  @Deprecated public java.lang.CharSequence hl7;
  @Deprecated public long helix_rcv_ts;
  @Deprecated public int tz_offset;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ObrAvroModel() {}

  /**
   * All-args constructor.
   */
  public ObrAvroModel(java.lang.Long msh_ts, java.lang.CharSequence source, java.lang.CharSequence msg_id, java.lang.CharSequence hl7, java.lang.Long helix_rcv_ts, java.lang.Integer tz_offset) {
    this.msh_ts = msh_ts;
    this.source = source;
    this.msg_id = msg_id;
    this.hl7 = hl7;
    this.helix_rcv_ts = helix_rcv_ts;
    this.tz_offset = tz_offset;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msh_ts;
    case 1: return source;
    case 2: return msg_id;
    case 3: return hl7;
    case 4: return helix_rcv_ts;
    case 5: return tz_offset;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msh_ts = (java.lang.Long)value$; break;
    case 1: source = (java.lang.CharSequence)value$; break;
    case 2: msg_id = (java.lang.CharSequence)value$; break;
    case 3: hl7 = (java.lang.CharSequence)value$; break;
    case 4: helix_rcv_ts = (java.lang.Long)value$; break;
    case 5: tz_offset = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'msh_ts' field.
   */
  public java.lang.Long getMshTs() {
    return msh_ts;
  }

  /**
   * Sets the value of the 'msh_ts' field.
   * @param value the value to set.
   */
  public void setMshTs(java.lang.Long value) {
    this.msh_ts = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'msg_id' field.
   */
  public java.lang.CharSequence getMsgId() {
    return msg_id;
  }

  /**
   * Sets the value of the 'msg_id' field.
   * @param value the value to set.
   */
  public void setMsgId(java.lang.CharSequence value) {
    this.msg_id = value;
  }

  /**
   * Gets the value of the 'hl7' field.
   */
  public java.lang.CharSequence getHl7() {
    return hl7;
  }

  /**
   * Sets the value of the 'hl7' field.
   * @param value the value to set.
   */
  public void setHl7(java.lang.CharSequence value) {
    this.hl7 = value;
  }

  /**
   * Gets the value of the 'helix_rcv_ts' field.
   */
  public java.lang.Long getHelixRcvTs() {
    return helix_rcv_ts;
  }

  /**
   * Sets the value of the 'helix_rcv_ts' field.
   * @param value the value to set.
   */
  public void setHelixRcvTs(java.lang.Long value) {
    this.helix_rcv_ts = value;
  }

  /**
   * Gets the value of the 'tz_offset' field.
   */
  public java.lang.Integer getTzOffset() {
    return tz_offset;
  }

  /**
   * Sets the value of the 'tz_offset' field.
   * @param value the value to set.
   */
  public void setTzOffset(java.lang.Integer value) {
    this.tz_offset = value;
  }

  /** Creates a new ObrAvroModel RecordBuilder */
  public static org.yale.comphealth.electron.models.ObrAvroModel.Builder newBuilder() {
    return new org.yale.comphealth.electron.models.ObrAvroModel.Builder();
  }
  
  /** Creates a new ObrAvroModel RecordBuilder by copying an existing Builder */
  public static org.yale.comphealth.electron.models.ObrAvroModel.Builder newBuilder(org.yale.comphealth.electron.models.ObrAvroModel.Builder other) {
    return new org.yale.comphealth.electron.models.ObrAvroModel.Builder(other);
  }
  
  /** Creates a new ObrAvroModel RecordBuilder by copying an existing ObrAvroModel instance */
  public static org.yale.comphealth.electron.models.ObrAvroModel.Builder newBuilder(org.yale.comphealth.electron.models.ObrAvroModel other) {
    return new org.yale.comphealth.electron.models.ObrAvroModel.Builder(other);
  }
  
  /**
   * RecordBuilder for ObrAvroModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ObrAvroModel>
    implements org.apache.avro.data.RecordBuilder<ObrAvroModel> {

    private long msh_ts;
    private java.lang.CharSequence source;
    private java.lang.CharSequence msg_id;
    private java.lang.CharSequence hl7;
    private long helix_rcv_ts;
    private int tz_offset;

    /** Creates a new Builder */
    private Builder() {
      super(org.yale.comphealth.electron.models.ObrAvroModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.yale.comphealth.electron.models.ObrAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msh_ts)) {
        this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source)) {
        this.source = data().deepCopy(fields()[1].schema(), other.source);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[2].schema(), other.msg_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.hl7)) {
        this.hl7 = data().deepCopy(fields()[3].schema(), other.hl7);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.helix_rcv_ts)) {
        this.helix_rcv_ts = data().deepCopy(fields()[4].schema(), other.helix_rcv_ts);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tz_offset)) {
        this.tz_offset = data().deepCopy(fields()[5].schema(), other.tz_offset);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ObrAvroModel instance */
    private Builder(org.yale.comphealth.electron.models.ObrAvroModel other) {
            super(org.yale.comphealth.electron.models.ObrAvroModel.SCHEMA$);
      if (isValidValue(fields()[0], other.msh_ts)) {
        this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source)) {
        this.source = data().deepCopy(fields()[1].schema(), other.source);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[2].schema(), other.msg_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.hl7)) {
        this.hl7 = data().deepCopy(fields()[3].schema(), other.hl7);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.helix_rcv_ts)) {
        this.helix_rcv_ts = data().deepCopy(fields()[4].schema(), other.helix_rcv_ts);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tz_offset)) {
        this.tz_offset = data().deepCopy(fields()[5].schema(), other.tz_offset);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'msh_ts' field */
    public java.lang.Long getMshTs() {
      return msh_ts;
    }
    
    /** Sets the value of the 'msh_ts' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setMshTs(long value) {
      validate(fields()[0], value);
      this.msh_ts = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'msh_ts' field has been set */
    public boolean hasMshTs() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'msh_ts' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearMshTs() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'source' field */
    public java.lang.CharSequence getSource() {
      return source;
    }
    
    /** Sets the value of the 'source' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.source = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'source' field has been set */
    public boolean hasSource() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'source' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearSource() {
      source = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'msg_id' field */
    public java.lang.CharSequence getMsgId() {
      return msg_id;
    }
    
    /** Sets the value of the 'msg_id' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setMsgId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.msg_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_id' field has been set */
    public boolean hasMsgId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'msg_id' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearMsgId() {
      msg_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'hl7' field */
    public java.lang.CharSequence getHl7() {
      return hl7;
    }
    
    /** Sets the value of the 'hl7' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setHl7(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.hl7 = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'hl7' field has been set */
    public boolean hasHl7() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'hl7' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearHl7() {
      hl7 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'helix_rcv_ts' field */
    public java.lang.Long getHelixRcvTs() {
      return helix_rcv_ts;
    }
    
    /** Sets the value of the 'helix_rcv_ts' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setHelixRcvTs(long value) {
      validate(fields()[4], value);
      this.helix_rcv_ts = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'helix_rcv_ts' field has been set */
    public boolean hasHelixRcvTs() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'helix_rcv_ts' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearHelixRcvTs() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'tz_offset' field */
    public java.lang.Integer getTzOffset() {
      return tz_offset;
    }
    
    /** Sets the value of the 'tz_offset' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder setTzOffset(int value) {
      validate(fields()[5], value);
      this.tz_offset = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'tz_offset' field has been set */
    public boolean hasTzOffset() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'tz_offset' field */
    public org.yale.comphealth.electron.models.ObrAvroModel.Builder clearTzOffset() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public ObrAvroModel build() {
      try {
        ObrAvroModel record = new ObrAvroModel();
        record.msh_ts = fieldSetFlags()[0] ? this.msh_ts : (java.lang.Long) defaultValue(fields()[0]);
        record.source = fieldSetFlags()[1] ? this.source : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.msg_id = fieldSetFlags()[2] ? this.msg_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.hl7 = fieldSetFlags()[3] ? this.hl7 : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.helix_rcv_ts = fieldSetFlags()[4] ? this.helix_rcv_ts : (java.lang.Long) defaultValue(fields()[4]);
        record.tz_offset = fieldSetFlags()[5] ? this.tz_offset : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
