/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.yale.comphealth.electron.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ObxAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ObxAvroModel\",\"namespace\":\"org.yale.comphealth.electron.models\",\"fields\":[{\"name\":\"msh_ts\",\"type\":\"long\"},{\"name\":\"alarm_ts\",\"type\":\"long\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"unit\",\"type\":\"string\"},{\"name\":\"bed\",\"type\":\"string\"},{\"name\":\"channel\",\"type\":\"string\"},{\"name\":\"text\",\"type\":\"string\"},{\"name\":\"msg_id\",\"type\":\"string\"},{\"name\":\"helix_rcv_ts\",\"type\":\"long\"},{\"name\":\"tz_offset\",\"type\":\"int\"},{\"name\":\"msg_line\",\"type\":\"int\"},{\"name\":\"msg_max_line\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long msh_ts;
  @Deprecated public long alarm_ts;
  @Deprecated public java.lang.CharSequence source;
  @Deprecated public java.lang.CharSequence unit;
  @Deprecated public java.lang.CharSequence bed;
  @Deprecated public java.lang.CharSequence channel;
  @Deprecated public java.lang.CharSequence text;
  @Deprecated public java.lang.CharSequence msg_id;
  @Deprecated public long helix_rcv_ts;
  @Deprecated public int tz_offset;
  @Deprecated public int msg_line;
  @Deprecated public int msg_max_line;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ObxAvroModel() {}

  /**
   * All-args constructor.
   */
  public ObxAvroModel(java.lang.Long msh_ts, java.lang.Long alarm_ts, java.lang.CharSequence source, java.lang.CharSequence unit, java.lang.CharSequence bed, java.lang.CharSequence channel, java.lang.CharSequence text, java.lang.CharSequence msg_id, java.lang.Long helix_rcv_ts, java.lang.Integer tz_offset, java.lang.Integer msg_line, java.lang.Integer msg_max_line) {
    this.msh_ts = msh_ts;
    this.alarm_ts = alarm_ts;
    this.source = source;
    this.unit = unit;
    this.bed = bed;
    this.channel = channel;
    this.text = text;
    this.msg_id = msg_id;
    this.helix_rcv_ts = helix_rcv_ts;
    this.tz_offset = tz_offset;
    this.msg_line = msg_line;
    this.msg_max_line = msg_max_line;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msh_ts;
    case 1: return alarm_ts;
    case 2: return source;
    case 3: return unit;
    case 4: return bed;
    case 5: return channel;
    case 6: return text;
    case 7: return msg_id;
    case 8: return helix_rcv_ts;
    case 9: return tz_offset;
    case 10: return msg_line;
    case 11: return msg_max_line;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msh_ts = (java.lang.Long)value$; break;
    case 1: alarm_ts = (java.lang.Long)value$; break;
    case 2: source = (java.lang.CharSequence)value$; break;
    case 3: unit = (java.lang.CharSequence)value$; break;
    case 4: bed = (java.lang.CharSequence)value$; break;
    case 5: channel = (java.lang.CharSequence)value$; break;
    case 6: text = (java.lang.CharSequence)value$; break;
    case 7: msg_id = (java.lang.CharSequence)value$; break;
    case 8: helix_rcv_ts = (java.lang.Long)value$; break;
    case 9: tz_offset = (java.lang.Integer)value$; break;
    case 10: msg_line = (java.lang.Integer)value$; break;
    case 11: msg_max_line = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'msh_ts' field.
   */
  public java.lang.Long getMshTs() {
    return msh_ts;
  }

  /**
   * Sets the value of the 'msh_ts' field.
   * @param value the value to set.
   */
  public void setMshTs(java.lang.Long value) {
    this.msh_ts = value;
  }

  /**
   * Gets the value of the 'alarm_ts' field.
   */
  public java.lang.Long getAlarmTs() {
    return alarm_ts;
  }

  /**
   * Sets the value of the 'alarm_ts' field.
   * @param value the value to set.
   */
  public void setAlarmTs(java.lang.Long value) {
    this.alarm_ts = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'unit' field.
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }

  /**
   * Sets the value of the 'unit' field.
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Gets the value of the 'bed' field.
   */
  public java.lang.CharSequence getBed() {
    return bed;
  }

  /**
   * Sets the value of the 'bed' field.
   * @param value the value to set.
   */
  public void setBed(java.lang.CharSequence value) {
    this.bed = value;
  }

  /**
   * Gets the value of the 'channel' field.
   */
  public java.lang.CharSequence getChannel() {
    return channel;
  }

  /**
   * Sets the value of the 'channel' field.
   * @param value the value to set.
   */
  public void setChannel(java.lang.CharSequence value) {
    this.channel = value;
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'msg_id' field.
   */
  public java.lang.CharSequence getMsgId() {
    return msg_id;
  }

  /**
   * Sets the value of the 'msg_id' field.
   * @param value the value to set.
   */
  public void setMsgId(java.lang.CharSequence value) {
    this.msg_id = value;
  }

  /**
   * Gets the value of the 'helix_rcv_ts' field.
   */
  public java.lang.Long getHelixRcvTs() {
    return helix_rcv_ts;
  }

  /**
   * Sets the value of the 'helix_rcv_ts' field.
   * @param value the value to set.
   */
  public void setHelixRcvTs(java.lang.Long value) {
    this.helix_rcv_ts = value;
  }

  /**
   * Gets the value of the 'tz_offset' field.
   */
  public java.lang.Integer getTzOffset() {
    return tz_offset;
  }

  /**
   * Sets the value of the 'tz_offset' field.
   * @param value the value to set.
   */
  public void setTzOffset(java.lang.Integer value) {
    this.tz_offset = value;
  }

  /**
   * Gets the value of the 'msg_line' field.
   */
  public java.lang.Integer getMsgLine() {
    return msg_line;
  }

  /**
   * Sets the value of the 'msg_line' field.
   * @param value the value to set.
   */
  public void setMsgLine(java.lang.Integer value) {
    this.msg_line = value;
  }

  /**
   * Gets the value of the 'msg_max_line' field.
   */
  public java.lang.Integer getMsgMaxLine() {
    return msg_max_line;
  }

  /**
   * Sets the value of the 'msg_max_line' field.
   * @param value the value to set.
   */
  public void setMsgMaxLine(java.lang.Integer value) {
    this.msg_max_line = value;
  }

  /** Creates a new ObxAvroModel RecordBuilder */
  public static org.yale.comphealth.electron.models.ObxAvroModel.Builder newBuilder() {
    return new org.yale.comphealth.electron.models.ObxAvroModel.Builder();
  }
  
  /** Creates a new ObxAvroModel RecordBuilder by copying an existing Builder */
  public static org.yale.comphealth.electron.models.ObxAvroModel.Builder newBuilder(org.yale.comphealth.electron.models.ObxAvroModel.Builder other) {
    return new org.yale.comphealth.electron.models.ObxAvroModel.Builder(other);
  }
  
  /** Creates a new ObxAvroModel RecordBuilder by copying an existing ObxAvroModel instance */
  public static org.yale.comphealth.electron.models.ObxAvroModel.Builder newBuilder(org.yale.comphealth.electron.models.ObxAvroModel other) {
    return new org.yale.comphealth.electron.models.ObxAvroModel.Builder(other);
  }
  
  /**
   * RecordBuilder for ObxAvroModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ObxAvroModel>
    implements org.apache.avro.data.RecordBuilder<ObxAvroModel> {

    private long msh_ts;
    private long alarm_ts;
    private java.lang.CharSequence source;
    private java.lang.CharSequence unit;
    private java.lang.CharSequence bed;
    private java.lang.CharSequence channel;
    private java.lang.CharSequence text;
    private java.lang.CharSequence msg_id;
    private long helix_rcv_ts;
    private int tz_offset;
    private int msg_line;
    private int msg_max_line;

    /** Creates a new Builder */
    private Builder() {
      super(org.yale.comphealth.electron.models.ObxAvroModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.yale.comphealth.electron.models.ObxAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msh_ts)) {
        this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alarm_ts)) {
        this.alarm_ts = data().deepCopy(fields()[1].schema(), other.alarm_ts);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bed)) {
        this.bed = data().deepCopy(fields()[4].schema(), other.bed);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.channel)) {
        this.channel = data().deepCopy(fields()[5].schema(), other.channel);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.text)) {
        this.text = data().deepCopy(fields()[6].schema(), other.text);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[7].schema(), other.msg_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.helix_rcv_ts)) {
        this.helix_rcv_ts = data().deepCopy(fields()[8].schema(), other.helix_rcv_ts);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.tz_offset)) {
        this.tz_offset = data().deepCopy(fields()[9].schema(), other.tz_offset);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.msg_line)) {
        this.msg_line = data().deepCopy(fields()[10].schema(), other.msg_line);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.msg_max_line)) {
        this.msg_max_line = data().deepCopy(fields()[11].schema(), other.msg_max_line);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ObxAvroModel instance */
    private Builder(org.yale.comphealth.electron.models.ObxAvroModel other) {
            super(org.yale.comphealth.electron.models.ObxAvroModel.SCHEMA$);
      if (isValidValue(fields()[0], other.msh_ts)) {
        this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alarm_ts)) {
        this.alarm_ts = data().deepCopy(fields()[1].schema(), other.alarm_ts);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bed)) {
        this.bed = data().deepCopy(fields()[4].schema(), other.bed);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.channel)) {
        this.channel = data().deepCopy(fields()[5].schema(), other.channel);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.text)) {
        this.text = data().deepCopy(fields()[6].schema(), other.text);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[7].schema(), other.msg_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.helix_rcv_ts)) {
        this.helix_rcv_ts = data().deepCopy(fields()[8].schema(), other.helix_rcv_ts);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.tz_offset)) {
        this.tz_offset = data().deepCopy(fields()[9].schema(), other.tz_offset);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.msg_line)) {
        this.msg_line = data().deepCopy(fields()[10].schema(), other.msg_line);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.msg_max_line)) {
        this.msg_max_line = data().deepCopy(fields()[11].schema(), other.msg_max_line);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'msh_ts' field */
    public java.lang.Long getMshTs() {
      return msh_ts;
    }
    
    /** Sets the value of the 'msh_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setMshTs(long value) {
      validate(fields()[0], value);
      this.msh_ts = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'msh_ts' field has been set */
    public boolean hasMshTs() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'msh_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearMshTs() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'alarm_ts' field */
    public java.lang.Long getAlarmTs() {
      return alarm_ts;
    }
    
    /** Sets the value of the 'alarm_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setAlarmTs(long value) {
      validate(fields()[1], value);
      this.alarm_ts = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'alarm_ts' field has been set */
    public boolean hasAlarmTs() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'alarm_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearAlarmTs() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'source' field */
    public java.lang.CharSequence getSource() {
      return source;
    }
    
    /** Sets the value of the 'source' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.source = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'source' field has been set */
    public boolean hasSource() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'source' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearSource() {
      source = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'unit' field */
    public java.lang.CharSequence getUnit() {
      return unit;
    }
    
    /** Sets the value of the 'unit' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.unit = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'unit' field has been set */
    public boolean hasUnit() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'unit' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'bed' field */
    public java.lang.CharSequence getBed() {
      return bed;
    }
    
    /** Sets the value of the 'bed' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setBed(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.bed = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'bed' field has been set */
    public boolean hasBed() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'bed' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearBed() {
      bed = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'channel' field */
    public java.lang.CharSequence getChannel() {
      return channel;
    }
    
    /** Sets the value of the 'channel' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setChannel(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.channel = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'channel' field has been set */
    public boolean hasChannel() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'channel' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearChannel() {
      channel = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'text' field */
    public java.lang.CharSequence getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setText(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.text = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'text' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearText() {
      text = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'msg_id' field */
    public java.lang.CharSequence getMsgId() {
      return msg_id;
    }
    
    /** Sets the value of the 'msg_id' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setMsgId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.msg_id = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_id' field has been set */
    public boolean hasMsgId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'msg_id' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearMsgId() {
      msg_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'helix_rcv_ts' field */
    public java.lang.Long getHelixRcvTs() {
      return helix_rcv_ts;
    }
    
    /** Sets the value of the 'helix_rcv_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setHelixRcvTs(long value) {
      validate(fields()[8], value);
      this.helix_rcv_ts = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'helix_rcv_ts' field has been set */
    public boolean hasHelixRcvTs() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'helix_rcv_ts' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearHelixRcvTs() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'tz_offset' field */
    public java.lang.Integer getTzOffset() {
      return tz_offset;
    }
    
    /** Sets the value of the 'tz_offset' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setTzOffset(int value) {
      validate(fields()[9], value);
      this.tz_offset = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'tz_offset' field has been set */
    public boolean hasTzOffset() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'tz_offset' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearTzOffset() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'msg_line' field */
    public java.lang.Integer getMsgLine() {
      return msg_line;
    }
    
    /** Sets the value of the 'msg_line' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setMsgLine(int value) {
      validate(fields()[10], value);
      this.msg_line = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_line' field has been set */
    public boolean hasMsgLine() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'msg_line' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearMsgLine() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'msg_max_line' field */
    public java.lang.Integer getMsgMaxLine() {
      return msg_max_line;
    }
    
    /** Sets the value of the 'msg_max_line' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder setMsgMaxLine(int value) {
      validate(fields()[11], value);
      this.msg_max_line = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_max_line' field has been set */
    public boolean hasMsgMaxLine() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'msg_max_line' field */
    public org.yale.comphealth.electron.models.ObxAvroModel.Builder clearMsgMaxLine() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public ObxAvroModel build() {
      try {
        ObxAvroModel record = new ObxAvroModel();
        record.msh_ts = fieldSetFlags()[0] ? this.msh_ts : (java.lang.Long) defaultValue(fields()[0]);
        record.alarm_ts = fieldSetFlags()[1] ? this.alarm_ts : (java.lang.Long) defaultValue(fields()[1]);
        record.source = fieldSetFlags()[2] ? this.source : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.unit = fieldSetFlags()[3] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.bed = fieldSetFlags()[4] ? this.bed : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.channel = fieldSetFlags()[5] ? this.channel : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.text = fieldSetFlags()[6] ? this.text : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.msg_id = fieldSetFlags()[7] ? this.msg_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.helix_rcv_ts = fieldSetFlags()[8] ? this.helix_rcv_ts : (java.lang.Long) defaultValue(fields()[8]);
        record.tz_offset = fieldSetFlags()[9] ? this.tz_offset : (java.lang.Integer) defaultValue(fields()[9]);
        record.msg_line = fieldSetFlags()[10] ? this.msg_line : (java.lang.Integer) defaultValue(fields()[10]);
        record.msg_max_line = fieldSetFlags()[11] ? this.msg_max_line : (java.lang.Integer) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
